import { type LEVEL } from "../types";
import { CHIP_OBJECT_ID } from "../tiles/objects";

export const level01: LEVEL = {
    "id": 1,
    "name": "Level 1",
    "terrain": [
        [
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1
        ],
        [
            1,
            0,
            0,
            1,
            2,
            1,
            0,
            0,
            1
        ],
        [
            1,
            0,
            0,
            1,
            3,
            1,
            0,
            0,
            1
        ],
        [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
        ],
        [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
        ],
        [
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1
        ],
        [
            1,
            0,
            0,
            1,
            0,
            1,
            0,
            0,
            1
        ],
        [
            1,
            0,
            0,
            1,
            0,
            1,
            0,
            0,
            1
        ],
        [
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1
        ]
    ],
    "objects": [
        [
            0,
            [
                4,
                7
            ]
        ],
        [
            0,
            [
                7,
                1
            ]
        ],
        [
            0,
            [
                1,
                4
            ]
        ]
    ],
    "monsters": [],
    "player": {
        "startX": 4,
        "startY": 4
    }
}